brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = true
error_on_line_overflow = true
fn_params_layout = "Compressed"
hex_literal_case = "upper"
imports_indent = "Visual"
indent_style = "Visual"
imports_granularity = "Module"
max_width = 120
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
